# A small, hand-written set of example reports per category, used to train
# the TensorFlow classifier at startup. Replace/extend this with real,
# anonymised historical complaint text before relying on this in production —
# classification quality scales directly with how much labelled text you feed it.

EXAMPLES = [
    # Water
    ("There has been no water in our street since yesterday morning.", "Water"),
    ("Our taps have been dry for three days now.", "Water"),
    ("Water supply has completely stopped in this area.", "Water"),
    ("There is a burst water pipe flooding the road.", "Water"),
    ("No water pressure at all from the municipal supply.", "Water"),
    ("The water main has burst outside the clinic.", "Water"),
    ("We have had zero water delivery for a week.", "Water"),
    ("The municipal water line has been dry since Monday.", "Water"),
    ("Water is leaking from a broken pipe beside the pavement.", "Water"),
    ("Residents are receiving brown water from the taps.", "Water"),
    ("The water tank in our neighbourhood has not been refilled.", "Water"),
    ("There is very low water pressure in all the houses on our street.", "Water"),
    ("The water meter outside our property is broken and leaking.", "Water"),
    ("Our block has had intermittent water supply since last week.", "Water"),
    ("The municipal tap at the taxi rank has no water.", "Water"),
    ("A water valve is leaking constantly near the sports ground.", "Water"),
    ("The water supply was cut off without any notice to residents.", "Water"),
    ("There is a strange smell coming from the municipal water.", "Water"),
    ("The overhead water tank is empty in our section of the settlement.", "Water"),
    ("Several homes on the hill have no water pressure.", "Water"),
    ("The water pipe under the sidewalk is leaking into the street.", "Water"),

    # Roads
    ("There is a huge pothole outside the school and cars keep getting damaged.", "Roads"),
    ("The road near the clinic has a massive pothole.", "Roads"),
    ("The tar road is badly cracked and breaking apart.", "Roads"),
    ("Several potholes have appeared after the rain on Main Road.", "Roads"),
    ("The gravel road is impassable after the storm.", "Roads"),
    ("A car damaged its tyre in a pothole near the taxi rank.", "Roads"),
    ("The potholes on Station Road are getting wider every week.", "Roads"),
    ("The road surface has washed away near the bridge.", "Roads"),
    ("A section of the pavement has broken and is difficult to drive over.", "Roads"),
    ("The road markings have faded and drivers cannot see the lanes.", "Roads"),
    ("A large crack runs across the road outside the library.", "Roads"),
    ("The pothole at the intersection is dangerous for motorcycles.", "Roads"),
    ("The shoulder of the road has eroded and is unsafe for pedestrians.", "Roads"),
    ("The dirt road to the settlement is full of deep ruts.", "Roads"),
    ("A fallen tree is blocking the entire road near the sports field.", "Roads"),
    ("The speed bumps have faded and are no longer visible at night.", "Roads"),
    ("The pavement outside the clinic is uneven and broken.", "Roads"),
    ("A manhole cover is missing from the middle of the road.", "Roads"),
    ("The bridge approach has become muddy and vehicles are getting stuck.", "Roads"),
    ("Road repairs were started but the open trench was left uncovered.", "Roads"),

    # Electricity
    ("We have had a power outage in our block for two days.", "Electricity"),
    ("There is an exposed live wire hanging near the pavement.", "Electricity"),
    ("The electricity substation keeps tripping every night.", "Electricity"),
    ("Our whole street lost power after the storm.", "Electricity"),
    ("The prepaid meter box is sparking and smoking.", "Electricity"),
    ("The power keeps going on and off in our neighbourhood.", "Electricity"),
    ("A utility pole is leaning dangerously over the road.", "Electricity"),
    ("Our prepaid electricity meter is not accepting the token.", "Electricity"),
    ("The transformer is making a loud noise and smells burnt.", "Electricity"),
    ("Several houses lost electricity after a cable was damaged.", "Electricity"),
    ("The electricity pole outside our house has a damaged cable.", "Electricity"),
    ("Our lights are flickering whenever appliances are switched on.", "Electricity"),
    ("The neighbourhood has had repeated scheduled power cuts.", "Electricity"),
    ("An electrical box has been left open beside the footpath.", "Electricity"),
    ("The meter for our home is showing an error and will not supply power.", "Electricity"),
    ("A fallen cable is lying across the entrance to the property.", "Electricity"),
    ("There has been no electricity at the community centre since yesterday.", "Electricity"),
    ("The power cable is rubbing against a tree near the houses.", "Electricity"),
    ("The electricity connection to our street has not been restored.", "Electricity"),

    # Street Lighting
    ("The street lights have been off for three nights.", "Street Lighting"),
    ("One streetlight outside our house is not working.", "Street Lighting"),
    ("All the lights along the avenue are out, it's very dark and unsafe.", "Street Lighting"),
    ("The traffic light at the intersection is not working.", "Street Lighting"),
    ("The lamp outside the community centre has stopped working.", "Street Lighting"),
    ("Streetlights on Oak Avenue switch off before sunrise.", "Street Lighting"),
    ("The pedestrian crossing light is broken near the school.", "Street Lighting"),
    ("A streetlight pole has been knocked over and needs replacement.", "Street Lighting"),
    ("The light at the bus stop is broken and commuters wait in darkness.", "Street Lighting"),
    ("Several lamps along the footpath are not turning on at night.", "Street Lighting"),
    ("The streetlight outside the pharmacy has been out for a month.", "Street Lighting"),
    ("A damaged lighting cable is hanging from the lamp post.", "Street Lighting"),
    ("The lights in the public square are not working after sunset.", "Street Lighting"),
    ("The light near the pedestrian bridge keeps switching off.", "Street Lighting"),
    ("The streetlamp is covered by tree branches and barely lights the road.", "Street Lighting"),
    ("There is no lighting along the road leading to the clinic.", "Street Lighting"),
    ("The lamp post outside the school is leaning and the light is broken.", "Street Lighting"),

    # Waste
    ("Illegal dumping is happening behind the shops every week.", "Waste"),
    ("Our bins have not been collected in two weeks.", "Waste"),
    ("There is rubbish piling up on the corner of the street.", "Waste"),
    ("The refuse truck skipped our area again this month.", "Waste"),
    ("Household waste has not been collected on our street.", "Waste"),
    ("A pile of rubbish is blocking the entrance to the park.", "Waste"),
    ("The public bins are overflowing near the market.", "Waste"),
    ("People are dumping broken furniture beside the river.", "Waste"),
    ("The recycling collection has not visited our neighbourhood this month.", "Waste"),
    ("A discarded mattress is blocking the pavement outside the shops.", "Waste"),
    ("The waste container near the station is damaged and overflowing.", "Waste"),
    ("Residents are burning rubbish in an illegal dumping area.", "Waste"),
    ("Garden waste has been left on the roadside for several weeks.", "Waste"),
    ("The rubbish collection schedule is not being followed on our street.", "Waste"),
    ("Plastic waste is scattered around the community sports ground.", "Waste"),
    ("A broken municipal bin has not been replaced outside the hall.", "Waste"),
    ("There is a growing pile of household rubbish near the stream.", "Waste"),

    # Sanitation
    ("There is sewage leaking into the road near the school.", "Sanitation"),
    ("The public toilets have been blocked for days and smell terrible.", "Sanitation"),
    ("Raw sewage is flowing through the community.", "Sanitation"),
    ("A sewage pipe has burst and is flooding the street with waste.", "Sanitation"),
    ("There is dirty water and sewage all over the street near the school.", "Sanitation"),
    ("The sewer manhole is overflowing outside several homes.", "Sanitation"),
    ("Our toilet drain is blocked and wastewater is backing up.", "Sanitation"),
    ("The sewage smell from the damaged pipe is affecting the whole block.", "Sanitation"),
    ("The ablution facilities at the taxi rank are unusable.", "Sanitation"),
    ("Wastewater is leaking from the sewer line behind the houses.", "Sanitation"),
    ("The sewer cover outside the shop is broken and smells bad.", "Sanitation"),
    ("Toilet waste is backing up into the bathroom of our home.", "Sanitation"),
    ("A blocked sewer is causing dirty water to pool in the street.", "Sanitation"),
    ("The public toilet at the park has no water and cannot be used.", "Sanitation"),
    ("A broken sewer pipe is contaminating the stream near the houses.", "Sanitation"),
    ("The sanitation service has not emptied the shared toilets.", "Sanitation"),
    ("The manhole is overflowing whenever residents use their toilets.", "Sanitation"),
    ("There is a strong sewage odour coming from the drain outside school.", "Sanitation"),
    ("The sewer connection is blocked and wastewater is entering the yard.", "Sanitation"),

    # Drainage
    ("The stormwater drain is blocked and the street floods every time it rains.", "Drainage"),
    ("Our yard keeps flooding because the drainage system is clogged.", "Drainage"),
    ("Water is not draining properly after rain, it stays for days.", "Drainage"),
    ("The storm drain on Main Street is covered with mud and debris.", "Drainage"),
    ("Rainwater is flowing into our homes because the channel is blocked.", "Drainage"),
    ("The culvert beside the road has collapsed and water cannot pass.", "Drainage"),
    ("Standing water remains outside the clinic after every rainfall.", "Drainage"),
    ("The open stormwater channel is filled with leaves and plastic.", "Drainage"),
    ("Floodwater is cutting across the road because the drain is too small.", "Drainage"),
    ("The drain outside our house is blocked with sand.", "Drainage"),
    ("Rainwater is washing soil into the street from the damaged channel.", "Drainage"),
    ("The stormwater grate is broken and poses a hazard to pedestrians.", "Drainage"),
    ("Water collects around the school gate because there is no drainage.", "Drainage"),
    ("A blocked culvert is causing flooding along the farm road.", "Drainage"),
    ("The drainage ditch has collapsed beside the residential road.", "Drainage"),
    ("The flood channel is full of weeds and cannot carry rainwater.", "Drainage"),

    # Infrastructure
    ("The community hall roof has collapsed and needs repair.", "Infrastructure"),
    ("The pedestrian bridge has a large crack and looks unsafe.", "Infrastructure"),
    ("The fence around the park is broken and falling down.", "Infrastructure"),
    ("The roof of the community centre leaks whenever it rains.", "Infrastructure"),
    ("The public playground equipment is damaged and unsafe.", "Infrastructure"),
    ("The bus shelter has been damaged and needs to be rebuilt.", "Infrastructure"),
    ("The retaining wall beside the library is starting to collapse.", "Infrastructure"),
    ("The roof at the public library is damaged and leaks inside.", "Infrastructure"),
    ("The community hall doors and windows are broken.", "Infrastructure"),
    ("The footbridge over the stream has loose boards.", "Infrastructure"),
    ("The fence around the sports field has fallen down.", "Infrastructure"),
    ("The public park benches are damaged and need repair.", "Infrastructure"),
    ("The bus shelter roof was blown away and has not been replaced.", "Infrastructure"),
    ("The retaining wall beside the road has large gaps in it.", "Infrastructure"),
    ("The community centre has no accessible ramp for wheelchair users.", "Infrastructure"),
    ("The public swimming pool building needs urgent structural repairs.", "Infrastructure"),

    # Other
    ("I would like to know when the next council meeting is scheduled.", "Other"),
    ("Can someone explain how to apply for an indigent grant.", "Other"),
    ("I have a general question about municipal billing.", "Other"),
    ("Where can I report a change of address on my municipal account?", "Other"),
    ("I need information about applying for a municipal service account.", "Other"),
    ("Please tell me the office hours for the customer service centre.", "Other"),
    ("How do residents submit feedback about a council service?", "Other"),
    ("Where can I find the municipal service application forms?", "Other"),
    ("I want to ask about the process for a property rates account.", "Other"),
    ("What documents are needed to register a new municipal account?", "Other"),
    ("Please provide the contact details for the municipal call centre.", "Other"),
    ("How can residents attend or watch the next council meeting?", "Other"),
    ("I need help understanding a notice on my municipal statement.", "Other"),
    ("Where should I send a general request for municipal information?", "Other"),
    ("Can the municipality explain the process for lodging a service query?", "Other"),
]
